### ISSUE TITLE
"PermissionError: [Errno 13] Permission denied"

### ISSUE THREAD

**Issue by v-amorim** [poemods/Path-of-Exile-modding-tool#4]
Any way to solve this? I tried changing the folder location, and enabling admin right (this made the program close automatically)

**Comment by CheesyFriend** [comment]
Right click your drive with poe and give all permissions to guest user.

Also it doesn't work with steam version, but you can go to your path of exile page and link your email to account. This will work like a login when you install standalone version of poe.

**Comment by echomokona** [comment]
Isn't giving full permissions to user 'guest' on c drive like using a tunnel excavation machine to drill a massive security hole into the system?

Please, let me know if there is an alternate solution that does not involve performing that step. Maybe guest permissions on the entire PoE folder instead of full drive? Thank you very much!

Edit1: I actually tried giving the permissions just to see what happened. In my case, the Permission Denied error still persists as of now. (16-jan-21, 4:34pm)

Edit2: Console output.

> Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\f\Path-of-Exile-modding-tool-master\poemods_threads.py", line 48, in actionthread
    self.modg.rescanggpk(vala[1], vala[2], True)
  File "C:\f\Path-of-Exile-modding-tool-master\poemods_ggpk.py", line 78, in rescanggpk
    self.gethash()
  File "C:\f\Path-of-Exile-modding-tool-master\poemods_ggpk.py", line 223, in gethash
    with open(self.ggpkname, "rb") as fin :
PermissionError: [Errno 13] Permission denied: 'C:\\f\\poe'

**Comment by atheran2** [comment]
I have the same problem as echomokona. Even running CMD as an elevated user and running __init__.py from there, I still get permission denied.
